--
-- Script was generated by Devart dbForge Studio for MySQL, Version 10.0.150.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15-Jan-25 11:27:49 AM
-- Server version: 8.3.0
--

SET NAMES 'utf8';

INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(1, 1, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(2, 1, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(3, 1, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(4, 2, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(5, 2, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(6, 2, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(7, 3, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(8, 3, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(9, 3, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(10, 4, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(11, 4, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(12, 4, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(13, 5, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(14, 5, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(15, 6, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(16, 6, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(17, 7, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(18, 7, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(19, 8, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(20, 8, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(21, 10, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(22, 9, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(23, 11, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(24, 12, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(25, 12, 4, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(26, 13, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(27, 13, 4, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(28, 14, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(29, 14, 4, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(30, 15, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(31, 15, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(32, 16, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(33, 16, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(34, 17, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(35, 17, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(36, 18, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(37, 19, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(38, 20, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(39, 21, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(40, 22, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(41, 23, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(42, 24, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(43, 25, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(44, 26, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(45, 27, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(46, 28, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(47, 29, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(48, 30, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(49, 31, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(50, 32, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(51, 33, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(52, 34, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(53, 35, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(54, 36, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(55, 36, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(56, 37, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(57, 37, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(58, 38, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(59, 38, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(60, 39, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(61, 39, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(62, 40, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(63, 40, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(64, 41, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(65, 41, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(66, 42, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(67, 42, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(68, 43, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(69, 43, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(73, 47, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(74, 48, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(75, 49, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(76, 50, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(77, 51, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(78, 54, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(79, 55, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(80, 56, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(81, 57, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(82, 58, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(83, 58, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(84, 59, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(85, 59, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(86, 60, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(87, 60, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(88, 61, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(89, 61, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(90, 62, 5, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(91, 63, 5, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(92, 64, 5, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(93, 65, 5, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(94, 66, 5, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(95, 67, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(96, 68, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(97, 69, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(98, 69, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(99, 70, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(100, 70, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(101, 71, 2, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(102, 71, 3, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(103, 72, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(104, 73, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(105, 74, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(106, 76, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(107, 79, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(108, 80, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(109, 81, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(110, 82, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(111, 83, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(112, 84, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(113, 85, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(114, 86, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(115, 87, 1, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(116, 88, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(117, 89, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(118, 90, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(119, 91, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(120, 92, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(121, 93, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(122, 94, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(123, 95, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(124, 96, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(125, 97, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(126, 100, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(127, 101, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(128, 102, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(129, 103, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(130, 104, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(131, 105, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(132, 75, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(133, 77, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(134, 78, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(135, 99, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(136, 98, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(137, 53, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(138, 52, 6, NULL, NULL);
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(139, 45, 7, '2025-01-15 11:21:55', '2025-01-15 11:21:55');
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(140, 46, 7, '2025-01-15 11:22:02', '2025-01-15 11:22:02');
INSERT INTO cdms.sources(id, person_id, form_id, created_at, updated_at) VALUES
(141, 44, 7, '2025-01-15 11:22:09', '2025-01-15 11:22:09');