<?php

namespace App\Traits;

trait FormEssentials
{
    //
    public $forms = [
        'Rtc Recruitment Form' => [
            'RTC Actor Recruitment' => [
                'ID' => 'Required, Unique,  Number',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Date of Recruitment' => 'Date (dd-mm-yyyy)',
                'Name of Actor' => 'Text',
                'Name of Representative' => 'Text',
                'Phone Number' => 'Text',
                'Type' => 'Text, (Choose one option)',
                'Group' => 'Text, (Choose one option)',
                'Approach' => 'Text, (Choose one option)',
                'Sector' => 'Text, (Choose one option)',
                'Members Female 18-35' => 'Number (>=0)',
                'Members Male 18-35' => 'Number (>=0)',
                'Members Male 35+' => 'Number (>=0)',
                'Members Female 35+' => 'Number (>=0)',
                'Category' => 'Text, (Choose one option)',
                'Establishment Status' => 'New/Old, (Choose one option)',
                'Is Registered' => 'Boolean (1/0)',
                'Registration Body' => 'Text',
                'Registration Number' => 'Text',
                'Registration Date' => 'Date (dd-mm-yyyy)',
                'Employees Formal Female 18-35' => 'Number (>=0)',
                'Employees Formal Male 18-35' => 'Number (>=0)',
                'Employees Formal Male 35+' => 'Number (>=0)',
                'Employees Formal Female 35+' => 'Number (>=0)',
                'Employees Informal Female 18-35' => 'Number (>=0)',
                'Employees Informal Male 18-35' => 'Number (>=0)',
                'Employees Informal Male 35+' => 'Number (>=0)',
                'Employees Informal Female 35+' => 'Number (>=0)',
                'Area Under Cultivation' => 'Number (>=0)',
                'Is Registered Seed Producer' => 'Boolean (1/0)',
                'Uses Certified Seed' => 'Boolean (1/0)',
            ],
            'Seed Services Unit' => [
                'ID' => 'Number, Exists in RTC Actor Recruitment Sheet',
                'Registration Date' => 'Date (dd-mm-yyyy)',
                'Registration Number' => 'Text',
                'Variety' => 'Text',
            ]
        ],
        'Rtc Production Farmers Form' => [
            'Production Farmers' => [
                'ID' => 'Required, Unique,  Number',
                'Group Name' => 'Required, Text',
                'Date Of Follow Up' => 'Required, Date (dd-mm-yyyy)',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Number of Plantlets Produced Cassava' => 'Number (>=0)',
                'Number of Plantlets Produced Potato' => 'Number (>=0)',
                'Number of Plantlets Produced Sweet Potato' => 'Number (>=0)',
                'Screen House Vines Harvested' => 'Number (>=0)',
                'Screen House Min Tubers Harvested' => 'Number (>=0)',
                'SAH Plants Produced' => 'Number (>=0)',
                'Is Registered Seed Producer' => 'Boolean (1/0)',
                'Seed Producer Registration Number' => 'Text',
                'Seed Producer Registration Date' => 'Date (dd-mm-yyyy)',
                'Uses Certified Seed' => 'Boolean (1/0)',
                'Market Segment Fresh' => 'Boolean (1/0)',
                'Market Segment Processed' => 'Boolean (1/0)',
                'Market Segment Seed' => 'Boolean (1/0)',
                'Market Segment Cuttings' => 'Boolean (1/0)',
                'Has RTC Market Contract' => 'Boolean (1/0)',
                'Total Volume Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Production Seed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Total Volume Production Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Produce' => 'Number (>=0),(in MT)',
                'Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Production Value Seed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Total Volume Irrigation Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Irrigation Production Seeed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Total Volume Irrigation Production Cuttings' => 'Number (>=0), (in MT)',
                'Irrigation Production Value Produce' => 'Number (>=0),(in MT)',
                'Irrigation Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Irrigation Production Value Seed' => 'Number (>=0), (in MT or Bundles depending enterprise)',
                'Irrigation Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Irrigation Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Irrigation Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Sells to Domestic Markets' => 'Boolean (1/0)',
                'Sells to International Markets' => 'Boolean (1/0)',
                'Uses Market Information Systems' => 'Boolean (1/0)',
                'Sells to Aggregation Centers' => 'Boolean (1/0)',
                'Total Volume Aggregation Center Sales' => 'Number (>=0)',
            ],
            'Contractual Agreements' => [
                'Farmer ID' => 'Number, Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Partner Name' => 'Required, Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Domestic Markets' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Required, Text, (Choose One)',
                'Market Name' => 'Required, Text',
                'District' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'International Markets' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Text, (Choose One)',
                'Market Name' => 'Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Market Information Systems' => [
                'Name' => 'Text',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Aggregation Centers' => [
                'Name' => 'Text',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Basic Seed' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Area' => 'Number (>=0)',
                'Variety' => 'Text',
            ],
            'Certified Seed' => [
                'Variety' => 'Text',
                'Area' => 'Number (>=0)',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Area Cultivation' => [
                'Variety' => 'Text',
                'Area' => 'Number (>=0)',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Seed Services Unit' => [
                'ID' => 'Number, Exists in Production Farmers Sheet',
                'Registration Date' => 'Date (dd-mm-yyyy)',
                'Registration Number' => 'Text',
                'Variety' => 'Text',
            ]
        ],
        'Rtc Production Processors Form' => [
            'Production Processors' => [
                'ID' => 'Required, Number',
                'Group Name' => 'Required, Text',
                'Date Of Follow Up' => 'Required, Date (dd-mm-yyyy)',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Market Segment Fresh' => 'Boolean (1/0)',
                'Market Segment Processed' => 'Boolean (1/0)',
                'Has RTC Market Contract' => 'Boolean (1/0)',
                'Total Volume Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Production Seeed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Total Volume Production Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Produce' => 'Number (>=0), (in MT)',
                'Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Production Value Seed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Sells to Domestic Markets' => 'Boolean (1/0)',
                'Sells to International Markets' => 'Boolean (1/0)',
                'Uses Market Info Systems' => 'Boolean (1/0)',
                'Sells to Aggregation Centers' => 'Boolean (1/0)',
                'Total Volume Aggregation Center Sales' => 'Number (>=0)',
            ],
            'Contractual Agreements' => [
                'Processor ID' => 'Number, Exists in Production Processors Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Partner Name' => 'Required, Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Domestic Markets' => [
                'Processor ID' => 'Exists in Production Processors Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Required, Text, (Choose One)',
                'Market Name' => 'Required, Text',
                'District' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'International Markets' => [
                'Processor ID' => 'Exists in Production Processors Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Text, (Choose One)',
                'Market Name' => 'Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Market Information Systems' => [
                'Name' => 'Text',
                'Processor ID' => 'Exists in Production Processors Sheet',
            ],
            'Aggregation Centers' => [
                'Name' => 'Text',
                'Processor ID' => 'Exists in Production Processors Sheet',
            ],
        ],
        'Rtc Consumption Form' => [
            'Rtc Consumption' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Entity Name' => 'Required, Text',
                'Entity Type' => 'Required, (Choose One)',
                'Date' => 'Date (dd-mm-yyyy)',
                'Cassava Crop' => 'Boolean (1/0)',
                'Potato Crop' => 'Boolean (1/0)',
                'Sweet Potato Crop' => 'Boolean (1/0)',
                'Male Count' => 'Number (>=0)',
                'Female Count' => 'Number (>=0)',
                'Number of Households' => 'Number (>=0), Only for CIP use',
            ]
        ],
        'Attendance Register Form' => [
            'Attendance Register' => [
                'Meeting Title' => 'Required, Text',
                'Meeting Category' => 'Required, Text, (Choose one option)',
                'Cassava' => 'Boolean (1/0)',
                'Potato' => 'Boolean (1/0)',
                'Sweet Potato' => 'Boolean (1/0)',
                'Venue' => 'Required, Text',
                'District' => 'Required, Text',
                'Start Date' => 'Required, Date (dd-mm-yyyy)',
                'End Date' => 'Required, Date (dd-mm-yyyy), After or equal to Start Date',
                'Total Days' => 'Number (>=1)',
                'Name' => 'Required, Text',
                'Sex' => 'Required, Male/Female',
                'Organization' => 'Text',
                'Designation' => 'Text',
                'Category' => 'Required, Text, (Choose one option)',
                'Phone Number' => 'Text',
                'Email' => 'Text',
            ]
        ],
        'Marketing Form' => [
            'Marketing Monthly Report' => [
                'Entry Month' => 'Date (dd-mm-yyyy)',
                'Off-taker Name/Vehicle Reg Number' => 'Text',
                'Trader Contact' => 'Text',
                'Buyer Location' => 'Text',
                'Variety Demanded' => 'Text',
                'Quality/Size' => 'Text',
                'Quantity' => 'Number (decimal)',
                'Units' => 'Text',
                'Estimated Demand (Kg)' => 'Number (decimal)',
                'Agreed Price per Kg (MWK)' => 'Number (decimal)',
                'Market Ordered From' => 'Text',
                'Final Market' => 'Text',
                'Final Market District' => 'Text',
                'Final Market Country' => 'Text',
                'Supply Frequency' => 'Text',
                'Estimated Total Value (MWK)' => 'Number (decimal)',
                'Estimated Total Value (USD)' => 'Number (decimal)',
            ]
        ],

        'Gross Margin Form' => [
            'Gross Profit' => [
                'ID' => 'Number, Required',

                'Gross Margin Title' => 'Text, Required',
                'Name of Producer' => 'Text',
                'Season' => 'Text',
                'Season Dates' => 'Text',
                'District' => 'Text',
                'Gender' => 'Text',
                'Phone Number' => 'Text',
                'GPS S' => 'Number ',
                'GPS E' => 'Number ',
                'Elevation' => 'Number',
                'Type of Produce' => 'Text',
                'EPA' => 'Text',
                'Section' => 'Text',
                'TA' => 'Text',
                'Selling Price Description' => 'Text',
                'Selling Price Quantity' => 'Number',
                'Selling Price Unit Price' => 'Number',
                'Selling Price' => 'Number',
                'Income Price Description' => 'Text',
                'Income Price Quantity' => 'Number',
                'Income Price Unit Price' => 'Number',
                'Income Price' => 'Number',
                'Total Valuable Costs' => 'Number',
                'Yield' => 'Number',
                'Break Even Yield' => 'Number',
                'Break Even Price' => 'Number',
                'Gross Margin' => 'Number',
            ],
            'Total Vaulable Costs' => [
                'Gross Margin ID' => 'Number, Required',
                'Item Name' => 'Text, Required',
                'Description' => 'Text',
                'Quantity' => 'Number',
                'Unit Price' => 'Number',
                'Total' => 'Number',
            ]
        ],
        'Seed Beneficiaries Form' => [
            'Potato' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Choose One (Single/Married/Separated/Widowed/Polygamy)',
                'Household Head' => 'Choose One (FHH/MHH/CHH)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Choose One (Male/Female)',
                'Group Name' => 'Text',
                'Type of Actor' => 'Choose One (Caregroup,School feeding,Commercial)',
                'Type of Plot' => 'Choose One (Mother,Baby,Ordinary demonstration)',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Seed Received in KGs' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ],
            'OFSP' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Choose One (Single/Married/Separated/Widowed/Polygamy)',
                'Household Head' => 'Choose One (FHH/MHH/CHH)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Choose One (Male/Female)',
                'Group Name' => 'Text',
                'Type of Actor' => 'Choose One (Caregroup,School feeding,Commercial)',
                'Type of Plot' => 'Choose One (Mother,Baby,Ordinary demonstration)',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Bundles Received' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ],
            'Cassava' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Choose One (Single/Married/Separated/Widowed/Polygamy)',
                'Household Head' => 'Choose One (FHH/MHH/CHH)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Choose One (Male/Female)',
                'Group Name' => 'Text',
                'Type of Actor' => 'Choose One (Caregroup,School feeding,Commercial)',
                'Type of Plot' => 'Choose One (Mother,Baby,Ordinary demonstration)',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Bundles Received' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ]
        ],

        'Progress summary Form' => [
            'Progress summary' => [
                "Indicator Number",
                "Indicator",
                "Disaggregation",
                "Y1 Target",
                "Y1 Achieved",
                "Y2 Target",
                "Y2 Achieved",
                "Y3 Target",
                "Y3 Achieved",
                "Y4 Target",
                "Y4 Achieved"
            ]
        ],

        'Root and Tuber Imports Form' => [

            'ROOTS & TUBER RAW IMPORTS' => [
                'Entry Border' => 'Required, Text',
                'Registration Date' => 'Required, Date (dd-mm-yyyy)',
                'TPIN' => 'Required, Text',
                'Importer Name' => 'Required, Text',
                'Year' => 'Required, Year',
                'HS Code' => 'Required, Text',
                'Tariff Description' => 'Optional, Text',
                'Commercial Description' => 'Optional, Text',
                'Package Kind' => 'Optional, Text',
                'Number of Packages' => 'Optional, Integer',
                'Origin' => 'Optional, Text',
                'Exporter' => 'Optional, Text',
                'Net Weight (Kgs)' => 'Optional, Decimal',
                'Foreign Currency' => 'Optional, Decimal',
                'Currency' => 'Optional, Text',
                'Exchange Rate' => 'Optional, Decimal',
                'Value for Duty (MWK)' => 'Optional, Decimal',
                'Other Information' => 'Optional, Text'
            ],
            'ROOTS & TUBER PROCESSED IMPORTS' => [
                'Entry Border' => 'Required, Text',
                'Registration Date' => 'Required, Date (dd-mm-yyyy)',
                'TPIN' => 'Required, Text',
                'Importer Name' => 'Required, Text',
                'Year' => 'Required, Year',
                'HS Code' => 'Required, Text',
                'Tariff Description' => 'Optional, Text',
                'Commercial Description' => 'Optional, Text',
                'Package Kind' => 'Optional, Text',
                'Number of Packages' => 'Optional, Integer',
                'Origin' => 'Optional, Text',
                'Net Weight (Kgs)' => 'Optional, Decimal',
                'Foreign Currency' => 'Optional, Decimal',
                'Currency' => 'Optional, Text',
                'Exchange Rate' => 'Optional, Decimal',
                'Value for Duty (MWK)' => 'Optional, Decimal',
                'Other Information' => 'Optional, Text'

            ]
        ],

        'Root and Tuber Exports Form' => [
            'ROOTS & TUBER RAW EXPORTS' => [
                'Registration Date' => 'Required, Date (dd-mm-yyyy)',
                'Year' => 'Required, Year',
                'Exporter Name' => 'Required, Text',
                'Consignee Name' => 'Optional, Text',
                'Quantity' => 'Optional, Integer',
                'Package Kind' => 'Optional, Text',
                'HS Code' => 'Required, Text',
                'Goods Description' => 'Optional, Text',
                'Commercial Goods Description' => 'Optional, Text',
                'Origin Country' => 'Optional, Text',
                'Exit Border' => 'Optional, Text',
                'Destination Country' => 'Optional, Text',
                'Net Weight (Kgs)' => 'Optional, Decimal',
                'Export Value (MWK)' => 'Optional, Decimal',
                'Other Information' => 'Optional, Text'
            ],
            'ROOTS & TUBER PROCESSED EXPORTS' => [
                'Registration Date' => 'Required, Date (dd-mm-yyyy)',
                'Year' => 'Required, Year',
                'Exporter Name' => 'Required, Text',
                'Consignee Name' => 'Optional, Text',
                'Quantity' => 'Optional, Integer',
                'Package Kind' => 'Optional, Text',
                'HS Code' => 'Required, Text',
                'Goods Description' => 'Optional, Text',
                'Commercial Goods Description' => 'Optional, Text',
                'Origin Country' => 'Optional, Text',
                'Exit Border' => 'Optional, Text',
                'Destination Country' => 'Optional, Text',
                'Net Weight (Kgs)' => 'Optional, Decimal',
                'Export Value (MWK)' => 'Optional, Decimal',
                'Other Information' => 'Optional, Text'
            ]
        ],
    ];
}
