<?php

namespace App\Traits;

trait FormEssentials
{
    //
    public $forms = [
        'Rtc Recruitment Form' => [
            'RTC Actor Recruitment' => [
                'ID' => 'Required, Unique,  Number',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Date of Recruitment' => 'Date (dd-mm-yyyy)',
                'Name of Actor' => 'Text',
                'Name of Representative' => 'Text',
                'Phone Number' => 'Text',
                'Type' => 'Text, (Choose one option)',
                'Group' => 'Text, (Choose one option)',
                'Approach' => 'Text, (Choose one option)',
                'Sector' => 'Text, (Choose one option)',
                'Members Female 18-35' => 'Number (>=0)',
                'Members Male 18-35' => 'Number (>=0)',
                'Members Male 35+' => 'Number (>=0)',
                'Members Female 35+' => 'Number (>=0)',
                'Category' => 'Text, (Choose one option)',
                'Establishment Status' => 'New/Old, (Choose one option)',
                'Is Registered' => 'Boolean (1/0)',
                'Registration Body' => 'Text',
                'Registration Number' => 'Text',
                'Registration Date' => 'Date (dd-mm-yyyy)',
                'Employees Formal Female 18-35' => 'Number (>=0)',
                'Employees Formal Male 18-35' => 'Number (>=0)',
                'Employees Formal Male 35+' => 'Number (>=0)',
                'Employees Formal Female 35+' => 'Number (>=0)',
                'Employees Informal Female 18-35' => 'Number (>=0)',
                'Employees Informal Male 18-35' => 'Number (>=0)',
                'Employees Informal Male 35+' => 'Number (>=0)',
                'Employees Informal Female 35+' => 'Number (>=0)',
                'Area Under Cultivation' => 'Number (>=0)',
                'Is Registered Seed Producer' => 'Boolean (1/0)',
                'Seed Producer Registration Number' => 'Text',
                'Seed Producer Registration Date' => 'Date (dd-mm-yyyy)',
                'Uses Certified Seed' => 'Boolean (1/0)',
            ],
            'Seed Services Unit' => [
                'Recruitment ID' => 'Number, Exists in Production Farmers Sheet',
                'Registration Date' => 'Date (dd-mm-yyyy)',
                'Registration Number' => 'Text',
                'Variety' => 'Text',
            ]
        ],
        'Rtc Production Farmers Form' => [
            'Production Farmers' => [
                'ID' => 'Required, Unique,  Number',
                'Group Name' => 'Required, Text',
                'Date Of Follow Up' => 'Required, Date (dd-mm-yyyy)',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Number of Plantlets Produced Cassava' => 'Number (>=0)',
                'Number of Plantlets Produced Potato' => 'Number (>=0)',
                'Number of Plantlets Produced Sweet Potato' => 'Number (>=0)',
                'Screen House Vines Harvested' => 'Number (>=0)',
                'Screen House Min Tubers Harvested' => 'Number (>=0)',
                'SAH Plants Produced' => 'Number (>=0)',
                'Is Registered Seed Producer' => 'Boolean (1/0)',
                'Seed Producer Registration Number' => 'Text',
                'Seed Producer Registration Date' => 'Date (dd-mm-yyyy)',
                'Uses Certified Seed' => 'Boolean (1/0)',
                'Market Segment Fresh' => 'Boolean (1/0)',
                'Market Segment Processed' => 'Boolean (1/0)',
                'Market Segment Seed' => 'Boolean (1/0)',
                'Market Segment Cuttings' => 'Boolean (1/0)',
                'Has RTC Market Contract' => 'Boolean (1/0)',
                'Total Volume Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Production Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Produce' => 'Number (>=0),(in MT)',
                'Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Production Value Seed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Total Volume Irrigation Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Irrigation Production Seeed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Total Volume Irrigation Production Cuttings' => 'Number (>=0), (in MT)',
                'Irrigation Production Value Produce' => 'Number (>=0),(in MT)',
                'Irrigation Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Irrigation Production Value Seed' => 'Number (>=0), (in MT or Bundles depending enterprise)',
                'Irrigation Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Irrigation Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Irrigation Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Sells to Domestic Markets' => 'Boolean (1/0)',
                'Sells to International Markets' => 'Boolean (1/0)',
                'Uses Market Information Systems' => 'Boolean (1/0)',
                'Sells to Aggregation Centers' => 'Boolean (1/0)',
                'Total Volume Aggregation Center Sales' => 'Number (>=0)',
            ],
            'Contractual Agreements' => [
                'Farmer ID' => 'Number, Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Partner Name' => 'Required, Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Domestic Markets' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Required, Text, (Choose One)',
                'Market Name' => 'Required, Text',
                'District' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'International Markets' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Required, Text, (Choose One)',
                'Market Name' => 'Required, Text',
                'District' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Market Information Systems' => [
                'Name' => 'Text',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Aggregation Centers' => [
                'Name' => 'Text',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Basic Seed' => [
                'Farmer ID' => 'Exists in Production Farmers Sheet',
                'Area' => 'Number (>=0)',
                'Variety' => 'Text',
            ],
            'Certified Seed' => [
                'Variety' => 'Text',
                'Area' => 'Number (>=0)',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
            'Area Cultivation' => [
                'Variety' => 'Text',
                'Area' => 'Number (>=0)',
                'Farmer ID' => 'Exists in Production Farmers Sheet',
            ],
        ],
        'Rtc Production Processors Form' => [
            'Production Processors' => [
                'ID' => 'Required, Number',
                'Group Name' => 'Required, Text',
                'Date Of Follow Up' => 'Required, Date (dd-mm-yyyy)',
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Enterprise' => 'Required, Text',
                'Market Segment Fresh' => 'Boolean (1/0)',
                'Market Segment Processed' => 'Boolean (1/0)',
                'Has RTC Market Contract' => 'Boolean (1/0)',
                'Total Volume Production Produce' => 'Number (>=0), (in MT)',
                'Total Volume Production Seeed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Total Volume Production Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Produce' => 'Number (>=0), (in MT)',
                'Production Value Produce Prevailing Price' => 'Number (>=0)',
                'Production Value Seed' => 'Number (>=0), (in MT or Bundles depending on enterprise)',
                'Production Value Seed Prevailing Price' => 'Number (>=0)',
                'Production Value Cuttings' => 'Number (>=0), (in MT)',
                'Production Value Cuttings Prevailing Price' => 'Number (>=0)',
                'Sells to Domestic Markets' => 'Boolean (1/0)',
                'Sells to International Markets' => 'Boolean (1/0)',
                'Uses Market Info Systems' => 'Boolean (1/0)',
                'Sells to Aggregation Centers' => 'Boolean (1/0)',
                'Total Volume Aggregation Center Sales' => 'Number (>=0)',
            ],
            'Contractual Agreements' => [
                'Processor ID' => 'Number, Exists in Production Processors Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Partner Name' => 'Required, Text',
                'Country' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'Domestic Markets' => [
                'Processor ID' => 'Exists in Production Processors Sheet',
                'Date Recorded' => 'Date (dd-mm-yyyy)',
                'Crop Type' => 'Required, Text, (Choose One)',
                'Market Name' => 'Required, Text',
                'District' => 'Text',
                'Date of Maximum Sale' => 'Date (dd-mm-yyyy)',
                'Product Type' => 'Text, (Choose One)',
                'Volume Sold Previous Period' => 'Number (>=0)',
                'Financial Value of Sales' => 'Number (>=0)',
            ],
            'International Markets' => [
                'Processor ID',
                'Date Recorded',
                'Crop Type',
                'Market Name',
                'Country',
                'Date of Maximum Sale',
                'Product Type',
                'Volume Sold Previous Period',
                'Financial Value of Sales'
            ],
            'Market Information Systems' => [
                'Name' => 'Text',
                'Processor ID' => 'Exists in Production Processors Sheet',
            ],
            'Aggregation Centers' => [
                'Name' => 'Text',
                'Processor ID' => 'Exists in Production Processors Sheet',
            ],
        ],
        'Rtc Consumption Form' => [
            'Rtc Consumption' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'District' => 'Required, Text',
                'Entity Name' => 'Required, Text',
                'Entity Type' => 'Required, Text',
                'Date' => 'Date (dd-mm-yyyy)',
                'Cassava Crop' => 'Boolean (1/0)',
                'Potato Crop' => 'Boolean (1/0)',
                'Sweet Potato Crop' => 'Boolean (1/0)',
                'Male Count' => 'Number (>=0)',
                'Female Count' => 'Number (>=0)',
            ]
        ],
        'Attendance Register Form' => [
            'Attendance Register' => [
                'Meeting Title' => 'Required, Text',
                'Meeting Category' => 'Required, Text, (Choose one option)',
                'Cassava' => 'Boolean (1/0)',
                'Potato' => 'Boolean (1/0)',
                'Sweet Potato' => 'Boolean (1/0)',
                'Venue' => 'Required, Text',
                'District' => 'Required, Text',
                'Start Date' => 'Required, Date (dd-mm-yyyy)',
                'End Date' => 'Required, Date (dd-mm-yyyy), After or equal to Start Date',
                'Total Days' => 'Number (>=1)',
                'Name' => 'Required, Text',
                'Sex' => 'Required, Male/Female',
                'Organization' => 'Text',
                'Designation' => 'Text',
                'Category' => 'Required, Text, (Choose one option)',
                'Phone Number' => 'Text',
                'Email' => 'Text',
            ]
        ],
        'Seed Beneficiaries Form' => [
            'Potato' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Number',
                'Household Head' => 'Number (>=1)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Male/Female or 1/2',
                'Group Name' => 'Text',
                'Type of Actor' => 'Number',
                'Name of Plot' => 'Number',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Seed Received' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ],
            'OFSP' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Number',
                'Household Head' => 'Number (>=1)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Male/Female or 1/2',
                'Group Name' => 'Text',
                'Type of Actor' => 'Number',
                'Name of Plot' => 'Number',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Bundles Received' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ],
            'Cassava' => [
                'EPA' => 'Required, Text',
                'Section' => 'Required, Text',
                'Name of AEDO' => 'Required, Text',
                'AEDO Phone Number' => 'Text',
                'Date of Distribution' => 'Date (dd-mm-yyyy)',
                'Year Of Distribution' => 'Number',
                'Name of Recipient' => 'Required, Text',
                'Village' => 'Text',
                'National ID' => 'Text',
                'District' => 'Required, Text',
                'Age' => 'Required, Number (>=1)',
                'Marital Status' => 'Number',
                'Household Head' => 'Number (>=1)',
                'Household Size' => 'Number (>=1)',
                'Children Under 5 in HH' => 'Number (>=0)',
                'Sex' => 'Required, Male/Female or 1/2',
                'Group Name' => 'Text',
                'Type of Actor' => 'Number',
                'Name of Plot' => 'Number',
                'Variety Received' => 'Text, (IF Multiple separate by commas)',
                'Amount of Seed Received' => 'Number(>=0)',
                'Phone Number' => 'Text',
                'Season Type' => 'Text, (Choose One)'
            ],
        ]
    ];
}
